<a href="https://colab.research.google.com/github/subratamondal1/Machine-Learning-Advanced/blob/main/Tensors_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors 
- Tensors are **multidimensional arrays**
- Ordered arrangement of numbers

Tensors can be :
- Zero Dimensional e.g 5 or 4 or 66
- 1 Dimensional e.g [1,4,5] or [8,6,8]
- 2 Dimensional e.g [[1,2,3],[4,5,6]]

In [5]:
import tensorflow as tf

## Initialization

### Zero Dimensional Tensor

In [6]:
# Zero dimensional Tensor
tensor_zero_dim = tf.constant(1)
print(tensor_zero_dim)

tf.Tensor(1, shape=(), dtype=int32)


In [10]:
print(tensor_zero_dim.shape)
print(tensor_zero_dim.ndim)

()
0


### One Dimensional Tensor
Form by stacking multiple Zero Dimensional Tensors

In [7]:
# One dimensional Tensor
tensor_one_dim = tf.constant([1,2,3])
print(tensor_one_dim)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [11]:
print(tensor_one_dim.shape)
print(tensor_one_dim.ndim)

(3,)
1


### Two Dimensional Tensor
Form by stacking multiple One Dimensional Tensors

In [8]:
# Two dimensional Tensor
tensor_two_dim = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor_two_dim)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [12]:
print(tensor_two_dim.shape)
print(tensor_two_dim.ndim)

(3, 3)
2


### Three Dimensional Tensor
Form by stacking multiple Two Dimensional Tensors

In [9]:
# Three dimensional Tensor
tensor_three_dim = tf.constant([
    [
    [1,2,3],
    [4,5,6]
    ],
    [
    [1,2,3],
    [4,5,6]
    ],
    [
    [1,2,3],
    [4,5,6]
    ],

])
print(tensor_three_dim)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]], shape=(3, 2, 3), dtype=int32)


In [13]:
print(tensor_three_dim.shape)
print(tensor_three_dim.ndim)

(3, 2, 3)
3


### Fourth Dimensional Tensor
Form by stacking multiple Three Dimensional Tensors

In [14]:
# Four dimensional Tensor
tensor_four_dim = tf.constant([
    [[
    [1,2,3],
    [4,5,6]
    ],
    [
    [1,2,3],
    [4,5,6]
    ],
    [
    [1,2,3],
    [4,5,6]
    ],],
    [[
    [1,2,3],
    [4,5,6]
    ],
    [
    [1,2,3],
    [4,5,6]
    ],
    [
    [1,2,3],
    [4,5,6]
    ],]
])
print(tensor_four_dim)

tf.Tensor(
[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]


 [[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]], shape=(2, 3, 2, 3), dtype=int32)


In [15]:
print(tensor_four_dim.shape)
print(tensor_four_dim.ndim)

(2, 3, 2, 3)
4


## Casting
```python
tf.cast(x, dtype, name=None)
```

In [17]:
print(tensor_two_dim)
casted_tensor_two_dim = tf.cast(tensor_two_dim, tf.int16)
print(casted_tensor_two_dim)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int16)


In [18]:
print(tensor_two_dim)
casted_tensor_two_dim = tf.cast(tensor_two_dim, tf.uint16)
print(casted_tensor_two_dim)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=uint16)


## Initializing

In [19]:
import numpy as np

In [22]:
x_np = np.array([1,2,3])
print(x_np)

[1 2 3]


## Convert to Tensor from Numpy array
```python
tf.convert_to_tensor(value, dtype=None, dtype_hint=None, name=None)
```

In [24]:
x_np_to_tensor = tf.convert_to_tensor(x_np)
print(x_np_to_tensor)

x_np_to_tensor = tf.convert_to_tensor(x_np, dtype=tf.int16)
print(x_np_to_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)
tf.Tensor([1 2 3], shape=(3,), dtype=int16)


## Identity Matrix
In case of Identity Matrix we assign value = 1 whenever column_position = row_position
```python
tf.eye(num_rows, num_columns=None, batch_shape=None, dtype=dtypes.float32, name=None)
```

In [30]:
identity_matrix = tf.eye(5, dtype = tf.float16)
print(identity_matrix)

identity_matrix = tf.eye(5,4, dtype = tf.float16)
print(identity_matrix)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float16)
tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]], shape=(5, 4), dtype=float16)


In [32]:
identity_matrix = tf.eye(3,3,batch_shape=[2], dtype = tf.float16)
print(identity_matrix)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float16)


## Fill Tensors
```python
tf.fill(dims, value, name=None)
```

In [34]:
fill_9 = tf.fill([3,3],9)
print(fill_9)

tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


## Ones
```python
tf.ones(shape, dtype=dtypes.float32, name=None)
```

In [36]:
ones_tensor = tf.ones([3,3])
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


## Ones Like

In [37]:
ones_like_four_dim = tf.ones_like(tensor_four_dim)
print(ones_like_four_dim)

tf.Tensor(
[[[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]], shape=(2, 3, 2, 3), dtype=int32)


## Random Normal Initializer
```python
tf.random_normal_initializer(
    mean=0.0, stddev=0.05, seed=None
)
```

In [39]:
random_normal = tf.random_normal_initializer(
    mean=0.0, stddev=0.05, seed=None
)

random_normal_tensor = random_normal([3,3])
print(random_normal_tensor)


tf.Tensor(
[[-0.0352075   0.0078643   0.0628294 ]
 [ 0.00621914  0.01839794 -0.10605025]
 [-0.00810497  0.05130358 -0.00872508]], shape=(3, 3), dtype=float32)


## Range Tensor
```python
tf.range(start, limit=None, delta=1, dtype=None, name='range')
```

In [41]:
range_tensor = tf.range(2,10)
print(range_tensor)

range_tensor = tf.range(2,10, delta=2)
print(range_tensor)

tf.Tensor([2 3 4 5 6 7 8 9], shape=(8,), dtype=int32)
tf.Tensor([2 4 6 8], shape=(4,), dtype=int32)
