<a href="https://colab.research.google.com/github/subratamondal1/Machine-Learning-Advanced/blob/main/Tensors_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors 
- Tensors are **multidimensional arrays**
- Ordered arrangement of numbers

Tensors can be :
- Zero Dimensional e.g 5 or 4 or 66
- 1 Dimensional e.g [1,4,5] or [8,6,8]
- 2 Dimensional e.g [[1,2,3],[4,5,6]]

In [1]:
import tensorflow as tf

## Initialization

### Zero Dimensional Tensor

In [2]:
# Zero dimensional Tensor
tensor_zero_dim = tf.constant(1)
print(tensor_zero_dim)

tf.Tensor(1, shape=(), dtype=int32)


In [3]:
print(tensor_zero_dim.shape)
print(tensor_zero_dim.ndim)

()
0


### One Dimensional Tensor
Form by stacking multiple Zero Dimensional Tensors

In [4]:
# One dimensional Tensor
tensor_one_dim = tf.constant([1,2,3])
print(tensor_one_dim)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [5]:
print(tensor_one_dim.shape)
print(tensor_one_dim.ndim)

(3,)
1


### Two Dimensional Tensor
Form by stacking multiple One Dimensional Tensors

In [6]:
# Two dimensional Tensor
tensor_two_dim = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor_two_dim)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [7]:
print(tensor_two_dim.shape)
print(tensor_two_dim.ndim)

(3, 3)
2


### Three Dimensional Tensor
Form by stacking multiple Two Dimensional Tensors

In [8]:
# Three dimensional Tensor
tensor_three_dim = tf.constant([
    [
    [1,2,3],
    [4,5,6]
    ],
    [
    [1,2,3],
    [4,5,6]
    ],
    [
    [1,2,3],
    [4,5,6]
    ],

])
print(tensor_three_dim)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]], shape=(3, 2, 3), dtype=int32)


In [9]:
print(tensor_three_dim.shape)
print(tensor_three_dim.ndim)

(3, 2, 3)
3


### Fourth Dimensional Tensor
Form by stacking multiple Three Dimensional Tensors

In [10]:
# Four dimensional Tensor
tensor_four_dim = tf.constant([
    [[
    [1,2,3],
    [4,5,6]
    ],
    [
    [1,2,3],
    [4,5,6]
    ],
    [
    [1,2,3],
    [4,5,6]
    ],],
    [[
    [1,2,3],
    [4,5,6]
    ],
    [
    [1,2,3],
    [4,5,6]
    ],
    [
    [1,2,3],
    [4,5,6]
    ],]
])
print(tensor_four_dim)

tf.Tensor(
[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]


 [[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]], shape=(2, 3, 2, 3), dtype=int32)


In [11]:
print(tensor_four_dim.shape)
print(tensor_four_dim.ndim)

(2, 3, 2, 3)
4


## Casting
```python
tf.cast(x, dtype, name=None)
```

In [12]:
print(tensor_two_dim)
casted_tensor_two_dim = tf.cast(tensor_two_dim, tf.int16)
print(casted_tensor_two_dim)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int16)


In [13]:
print(tensor_two_dim)
casted_tensor_two_dim = tf.cast(tensor_two_dim, tf.uint16)
print(casted_tensor_two_dim)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=uint16)


## Initializing

In [14]:
import numpy as np

In [15]:
x_np = np.array([1,2,3])
print(x_np)

[1 2 3]


## Convert to Tensor from Numpy array
```python
tf.convert_to_tensor(value, dtype=None, dtype_hint=None, name=None)
```

In [16]:
x_np_to_tensor = tf.convert_to_tensor(x_np)
print(x_np_to_tensor)

x_np_to_tensor = tf.convert_to_tensor(x_np, dtype=tf.int16)
print(x_np_to_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)
tf.Tensor([1 2 3], shape=(3,), dtype=int16)


## Identity Matrix
In case of Identity Matrix we assign value = 1 whenever column_position = row_position
```python
tf.eye(num_rows, num_columns=None, batch_shape=None, dtype=dtypes.float32, name=None)
```

In [17]:
identity_matrix = tf.eye(5, dtype = tf.float16)
print(identity_matrix)

identity_matrix = tf.eye(5,4, dtype = tf.float16)
print(identity_matrix)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float16)
tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]], shape=(5, 4), dtype=float16)


In [18]:
identity_matrix = tf.eye(3,3,batch_shape=[2], dtype = tf.float16)
print(identity_matrix)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float16)


## Fill Tensors
```python
tf.fill(dims, value, name=None)
```

In [19]:
fill_9 = tf.fill([3,3],9)
print(fill_9)

tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


## Ones
```python
tf.ones(shape, dtype=dtypes.float32, name=None)
```

In [20]:
ones_tensor = tf.ones([3,3])
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


## Ones Like

In [21]:
ones_like_four_dim = tf.ones_like(tensor_four_dim)
print(ones_like_four_dim)

tf.Tensor(
[[[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]], shape=(2, 3, 2, 3), dtype=int32)


## Random Normal Initializer
```python
tf.random_normal_initializer(
    mean=0.0, stddev=0.05, seed=None
)
```

In [22]:
random_normal = tf.random_normal_initializer(
    mean=0.0, stddev=0.05, seed=None
)

random_normal_tensor = random_normal([3,3])
print(random_normal_tensor)


tf.Tensor(
[[ 0.06272487  0.00014362  0.01923815]
 [-0.02408756 -0.01294771 -0.10510434]
 [ 0.00880159  0.09291355  0.08611438]], shape=(3, 3), dtype=float32)


## Range Tensor
```python
tf.range(start, limit=None, delta=1, dtype=None, name='range')
```

In [23]:
range_tensor = tf.range(2,10)
print(range_tensor)

range_tensor = tf.range(2,10, delta=2)
print(range_tensor)

tf.Tensor([2 3 4 5 6 7 8 9], shape=(8,), dtype=int32)
tf.Tensor([2 4 6 8], shape=(4,), dtype=int32)


## Tensor Shape
```python
tf.shape(input, out_type=dtypes.int32, name=None)
```

In [24]:
print(tf.shape(tensor_four_dim))
print(tensor_four_dim.shape)

tf.Tensor([2 3 2 3], shape=(4,), dtype=int32)
(2, 3, 2, 3)


## Tensor Size
```python
tf.size(input, out_type=dtypes.int32, name=None)
```

In [25]:
print(tf.size(tensor_four_dim))

tf.Tensor(36, shape=(), dtype=int32)


## Random Generator
```python
tf.random.Generator
```

In [26]:
# non_deterministic_state
g = tf.random.Generator.from_non_deterministic_state()
g.normal([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.38660228, -0.36674067, -0.57759047],
       [ 0.18976256, -0.9500818 , -0.97106   ],
       [-1.3394158 ,  0.6468262 , -1.1168596 ]], dtype=float32)>

In [27]:
g = tf.random.Generator.from_seed(44)
g.normal([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7535805 , -0.57166284,  0.1480774 ],
       [-0.23362993, -0.3522796 ,  0.40621263],
       [-1.0523509 ,  1.2054597 ,  1.6874489 ]], dtype=float32)>

In [28]:
g.uniform([3,3], minval=5, maxval=10)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[9.4899845, 6.105037 , 5.2075167],
       [6.480558 , 9.863672 , 8.113667 ],
       [6.1707153, 8.707638 , 5.3802943]], dtype=float32)>

## Tensor Indexed

In [30]:
tensor_indexed = tf.constant([4,5,6,7,8,9])
print(tensor_indexed[0:4])
print(tensor_indexed[2:5])

tf.Tensor([4 5 6 7], shape=(4,), dtype=int32)
tf.Tensor([6 7 8], shape=(3,), dtype=int32)


In [31]:
tf.range(2,8)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7], dtype=int32)>

In [32]:
tf.range(2,8,2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>