<a href="https://colab.research.google.com/github/subratamondal1/Machine-Learning-Advanced/blob/main/Tensors_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors 
- Tensors are **multidimensional arrays**
- Ordered arrangement of numbers

Tensors can be :
- Zero Dimensional e.g 5 or 4 or 66
- 1 Dimensional e.g [1,4,5] or [8,6,8]
- 2 Dimensional e.g [[1,2,3],[4,5,6]]

In [1]:
import tensorflow as tf

In [2]:
# Zero dimensional Tensor
tensor_zero_dim = tf.constant(1)
print(tensor_zero_dim)

tf.Tensor(1, shape=(), dtype=int32)


In [3]:
# One dimensional Tensor
tensor_one_dim = tf.constant([1,2,3])
print(tensor_one_dim)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [4]:
# Two dimensional Tensor
tensor_two_dim = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor_two_dim)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [6]:
# Three dimensional Tensor
tensor_three_dim = tf.constant([
    [
    [1,2,3],
    [4,5,6]
    ],
    [
    [1,2,3],
    [4,5,6]
    ],
    [
    [1,2,3],
    [4,5,6]
    ],

])
print(tensor_three_dim)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]], shape=(3, 2, 3), dtype=int32)
